# File name: DayPlanner1.kv
# :kivy 1.11.1
# by Nicholas Nord

<CustomAnchorLayout>:
    orientation: "Center"
    Button:
        pos: 100,0
        size: 100,100
        color: 0, 1, 0, 1
        text: 'Add Action'
        font_size:'20sp'
        number: 1

<CustomWidgets>
    Button:
        pos: 0,0
        size: 100,100
        color: 1, 0, 0, 1
        text: 'x'
        font_size:'30sp'
        number: 0
